SAT.UI.MVC/Controllers/UserAdminController.cs
using SAT.UI.MVC.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SAT.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

SAT.UI.MVC/Views/UsersAdmin/Create.cshtml
@model SAT.UI.MVC.Models.RegisterViewModel
@{
    ViewBag.Title = "Create New User";
}


<div class="card card-body max800 drop p-5">
    <h2 class="text-center pb-4">@ViewBag.Title</h2>
    <div class="divCenter">
        @using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-error" })
            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control min350" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Password, new { @class = "control-label" })
                @Html.PasswordFor(m => m.Password, new { @class = "form-control min350" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "control-label" })
                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control min350" })
            </div>
            <div class="form-group">
                <h4 class="text-center p-3">Select User Roles</h4>
                <div class=" text-center">
                    @foreach (var item in (SelectList)ViewBag.RoleId)
                    {
                        <span class="pl-3 pr-3">
                            <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                            @Html.Label(item.Value, new { @class = "control-label" })
                        </span>
                    }
                </div>
            </div>
            <div class="form-group text-center">
                <div class="pt-4">
                    <input type="submit" class="btn btn-primary btn80" value="Create" />
                    <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-primary btn80">Cancel</a>
                </div>
            </div>
        }
    </div>
</div>

SAT.UI.MVC/Views/UsersAdmin/Delete.cshtml
@model SAT.UI.MVC.Models.ApplicationUser

@{
    ViewBag.Title = "Delete User";
}

<div class="card card-body max800 drop p-5 text-center">
    <h2 class="text-center pb-0">@ViewBag.Title</h2>
    <h3 class="text-center pb-0">@Model.UserName</h3>

    <h3 class="text-danger pt-3">Are you sure you want to delete this User?</h3>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions pt-2">
            <input type="submit" value="Yes" class="btn btn-primary btn80" />
            <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-primary btn80">No</a>
        </div>
    }
</div>

SAT.UI.MVC/Views/UsersAdmin/Details.cshtml
@model SAT.UI.MVC.Models.ApplicationUser

@{
    ViewBag.Title = "User Details";
}

<div class="card card-body max800 drop">
    <h2 class="text-center pb-0">@ViewBag.Title</h2>
    <h2 class="text-center pb-2">
         @Html.DisplayFor(model => model.UserName)
    </h2>
    <div class="divCenter p-5 text-center">
        <dl class="dl-horizontal">
            <h4>
                User Name
            </h4>
            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>
        </dl>
        <h4 class="pt-3">List of roles for this user</h4>
        @if (ViewBag.RoleNames.Count == 0)
        {
            <hr />
            <p>No roles found for this user.</p>
        }
        <table class="table">
            @foreach (var item in ViewBag.RoleNames)
            {
                <tr>
                    <td>
                        @item
                    </td>
                </tr>
            }
        </table>
        <div class="pt-3">
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary btn80" })
            <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-primary btn80 mr-0">Return</a>
        </div>
    </div>
</div>

SAT.UI.MVC/Views/UsersAdmin/Edit.cshtml
@model SAT.UI.MVC.Models.EditUserViewModel

@{
    ViewBag.Title = "Edit User Account";
}

<div class="card card-body max800 drop">
    <h2 class="text-center pb-2">@ViewBag.Title</h2>
    <div class="divCenter p-4 text-center">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.Id)

                <div class="form-group inFix min350">
                    <h4>User Email</h4>
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control text-center" })
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
                <div class="form-group pt-3 text-center inFix">
                    <h4>User Roles</h4>
                    <p class="pt-1">
                        @foreach (var item in Model.RolesList)
                        {
                            <span class="pl-3 pr-3">
                                <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                                @Html.Label(item.Value, new { @class = "control-label" })
                            </span>
                        }
                    </p>
                </div>
                <div class="form-group">
                    <div class="pt-4">
                        <input type="submit" value="Save" class="btn btn-primary btn80" />
                        @*@Html.ActionLink("Cancel", "Index", "UsersAdmin", new { @class = "btn btn-primary btn80 mr-0" })*@
                        <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-primary btn80 mr-0">Cancel</a>
                    </div>
                </div>
            </div>
        }



    </div>
</div>

SAT.UI.MVC/Views/UsersAdmin/Index.cshtml
@model IEnumerable<SAT.UI.MVC.Models.ApplicationUser>

@{
    ViewBag.Title = "User Accounts";
}
<div class="card card-body max800">
    <h2 class="text-center pb-4">@ViewBag.Title</h2>
    <table class="table table-striped">
        <tr>
            <th>
                User Name
            </th>
            <th class="text-right">
                @Html.ActionLink("Create New Account", "Create")
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td class="text-right">
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</div>