SAT.UI.MVC/Controllers/StudentStatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAT.DATA.EF;

namespace SAT.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StudentStatusController : Controller
    {
        private SATEntities db = new SATEntities();

        // GET: StudentStatus
        public ActionResult Index()
        {
            return View(db.StudentStatuses.ToList());
        }

        public ActionResult IndexTiles()
        {
            return View(db.StudentStatuses.ToList());
        }

        // GET: StudentStatus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentStatus studentStatus = db.StudentStatuses.Find(id);
            if (studentStatus == null)
            {
                return HttpNotFound();
            }
            return View(studentStatus);
        }

        // GET: StudentStatus/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudentStatus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SSID,SSName,SSDescription")] StudentStatus studentStatus)
        {
            if (ModelState.IsValid)
            {
                db.StudentStatuses.Add(studentStatus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(studentStatus);
        }

        // GET: StudentStatus/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentStatus studentStatus = db.StudentStatuses.Find(id);
            if (studentStatus == null)
            {
                return HttpNotFound();
            }
            return View(studentStatus);
        }

        // POST: StudentStatus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SSID,SSName,SSDescription")] StudentStatus studentStatus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studentStatus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(studentStatus);
        }

        // GET: StudentStatus/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentStatus studentStatus = db.StudentStatuses.Find(id);
            if (studentStatus == null)
            {
                return HttpNotFound();
            }
            return View(studentStatus);
        }

        // POST: StudentStatus/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StudentStatus studentStatus = db.StudentStatuses.Find(id);
            db.StudentStatuses.Remove(studentStatus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAT.UI.MVC/Views/StudentStatus/Create.cshtml
@model SAT.DATA.EF.StudentStatus

@{
    ViewBag.Title = "Create Student Status";
}


<div class="card card-body max1000 drop">
    <h2 class="text-center pb-4">@ViewBag.Title</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal p-5">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.SSID)
            <div class="form-group inFix">
                @Html.LabelFor(model => model.SSName, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.SSName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group inFix">
                @Html.LabelFor(model => model.SSDescription, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.SSDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSDescription, "", new { @class = "text-danger" })
            </div>
            <div class="form-group mb-0">
                <div class="text-right col-md-12 p-0 pt-4">
                    <input type="submit" value="Save" class="btn btn-primary btn80" />
                    @*@Html.ActionLink("Cancel", "Index", "StudentStatus", new { @class = "btn btn-primary btn80 mr-0" })*@
                    <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-primary btn80 mr-0">Cancel</a>
                </div>
            </div>
        </div>
    }
</div>

SAT.UI.MVC/Views/StudentStatus/Delete.cshtml
@model SAT.DATA.EF.StudentStatus

@{
    ViewBag.Title = "Delete: " + Model.SSName;
}

<div class="card card-body max800 drop">
    <h2 class="text-center pb-2">@ViewBag.Title</h2>
    <div class="divCenter">
        <dl class="dl-horizontal">
            <div class="p-5">
                <dd>
                    <span class="font-weight-bold pr-2">Status Name:</span>  @Html.DisplayFor(model => model.SSName)
                </dd>
                <dd>
                    <span class="font-weight-bold pr-2">Description:</span>   @Html.DisplayFor(model => model.SSDescription)
                </dd>
            </div>
            <h3 class="text-center text-danger">Are you sure you want to delete: <span class="font-italic"> @Model.SSName</span>?</h3>
        </dl>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color text-center">
            <input type="submit" value="Yes" class="btn btn-primary btn80" />
            @*@Html.ActionLink("No", "Index", "StudentStatuses", new { @class = "btn btn-primary btn80" })*@
            <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-primary btn80">No</a>
        </div>
    }
</div>

SAT.UI.MVC/Views/StudentStatus/Details.cshtml
@model SAT.DATA.EF.StudentStatus

@{
    ViewBag.Title = "Student Status Details";
}


<div class="card card-body max800 drop">
    <h2 class="text-center pb-4">@ViewBag.Title</h2>
    <div class="divCenter">
        <dl class="dl-horizontal p-5">
            <dt>
                @Html.DisplayNameFor(model => model.SSName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.SSName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.SSDescription)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.SSDescription)
            </dd>
        </dl>
    </div>
    <p class="text-center">
        @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Edit", "Edit", new { id = Model.SSID }, new { @class = "btn btn-primary btn80" })
            @Html.ActionLink("Delete", "Delete", new { id = Model.SSID }, new { @class = "btn btn-primary btn80 ml-2" })
        }
        @*@Html.ActionLink("Cancel", "Index", "StudentStatus", new { @class = "btn btn-primary btn80" })*@
        <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-primary btn80 mr-0">Cancel</a>
    </p>
</div>

SAT.UI.MVC/Views/StudentStatus/Edit.cshtml
@model SAT.DATA.EF.StudentStatus

@{
    ViewBag.Title = "Edit Student Status: " + Model.SSName;
}


<div class="card card-body max1000 drop">
    <h2 class="text-center pb-4">@ViewBag.Title</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal p-5">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.SSID)
            <div class="form-group inFix">
                @Html.LabelFor(model => model.SSName, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.SSName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group inFix">
                @Html.LabelFor(model => model.SSDescription, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.SSDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSDescription, "", new { @class = "text-danger" })
            </div>
            <div class="form-group mb-0">
                <div class="text-right col-md-12 p-0 pt-4">
                    <input type="submit" value="Save" class="btn btn-primary btn80" />
                    @Html.ActionLink("Delete", "Delete", "StudentStatus", new { id = Model.SSID }, new { @class = "btn btn-primary btn80" })
                    @*@Html.ActionLink("Cancel", "Index", "StudentStatus", new { @class = "btn btn-primary btn80 mr-0" })*@
                    <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-primary btn80 mr-0">Cancel</a>
                </div>
            </div>
        </div>
    }
</div>

SAT.UI.MVC/Views/StudentStatus/Index.cshtml
@model IEnumerable<SAT.DATA.EF.StudentStatus>

@{
    ViewBag.Title = "Student Status";
}

<div class="card card-body max1000 drop">
    <h2 class="text-center">@ViewBag.Title</h2>
    <div class="text-center pb-4">
        @Html.ActionLink("Tiled View", "IndexTiles")
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.SSName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SSDescription)
                </th>
                <th class="text-right">
                    @Html.ActionLink("Create New Status", "Create")
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.SSName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SSDescription)
                    </td>
                    <td class="text-right">
                        @Html.ActionLink("Delete", "Delete", new { id = item.SSID }) <span>|</span>
                        @Html.ActionLink("Edit", "Edit", new { id = item.SSID }) <span>|</span>
                        @Html.ActionLink("Details", "Details", new { id = item.SSID })

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

SAT.UI.MVC/Views/StudentStatus/IndexTiles.cshtml
@model IEnumerable<SAT.DATA.EF.StudentStatus>

@{
    ViewBag.Title = "Student Status : Tiled";
}

<div class="max1000">
    <div class="card card-body drop mb-4">
        <h2 class="text-center">@ViewBag.Title</h2>
        <div class="text-center pb-4">
            @Html.ActionLink("List View", "Index")
        </div>
        <div class="text-right">
            @Html.ActionLink("Create New Status", "Create")
        </div>
    </div>
    <div class="m-auto">
        <div class="card-deck">
            @foreach (var item in Model)
            {
                <div class="grid-margin d-flex col-lg-6 text-center">
                    <div class="card card-body drop">
                        <h4 class="card-header">
                            <a href="@Url.Action("Details", new { id=item.SSID })" class="text-muted text-center">
                                @Html.DisplayFor(modelItem => item.SSName)
                            </a>
                        </h4>
                        <span></span>
                        @Html.DisplayNameFor(model => model.SSDescription)
                        @Html.DisplayFor(modelItem => item.SSDescription)
                        <div class="card-footer text-center d-flex justify-content-around">
                            @Html.ActionLink(" ", "Delete", new { id = item.SSID }, new { @class = "btn btn80 btn-outline-danger mdi mdi-delete" })
                            @Html.ActionLink(" ", "Edit", new { id = item.SSID }, new { @class = "btn btn80 btn-outline-secondary mdi mdi-lead-pencil" })
                        </div>
                    </div>
                </div>

            }

        </div>
    </div>
</div>