SAT.UI.MVC/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAT.DATA.EF;

namespace SAT.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    
    public class CoursesController : Controller
    {
        private SATEntities db = new SATEntities();

        // GET: Courses
        public ActionResult Index()
        {
            return RedirectToAction("Active");
        }

        public ActionResult Active()
        {
            return View(db.Courses.Where(x => x.IsActive == true).ToList());
        }

        public ActionResult Retired()
        {
            return View(db.Courses.Where(x => x.IsActive == false).ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseId,CourseName,CourseDescription,CreditHours,Curriculum,Notes,IsActive")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(course);
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseId,CourseName,CourseDescription,CreditHours,Curriculum,Notes,IsActive")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            //db.Courses.Remove(course);

            course.IsActive = !course.IsActive;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAT.UI.MVC/Controllers/ScheduledClassesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAT.DATA.EF;

namespace SAT.UI.MVC.Controllers
{
    
    public class ScheduledClassesController : Controller
    {
        private SATEntities db = new SATEntities();

        // GET: ScheduledClasses
        [Authorize(Roles = "Admin,Scheduler")]
        public ActionResult Index()
        {
            var scheduledClasses = db.ScheduledClasses.Include(s => s.Course).Include(s => s.ScheduledClassStatus);            
            return View(scheduledClasses.ToList());
        }

        // GET: ScheduledClasses/Details/5
        [Authorize(Roles = "Admin,Scheduler")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduledClass scheduledClass = db.ScheduledClasses.Find(id);
            if (scheduledClass == null)
            {
                return HttpNotFound();
            }
            return View(scheduledClass);
        }

        [Authorize(Roles = "Admin,Scheduler")]
        // GET: ScheduledClasses/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName");
            ViewBag.SCSID = new SelectList(db.ScheduledClassStatuses, "SCSID", "SCSName");
            return View();
        }

        // POST: ScheduledClasses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,Scheduler")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ScheduledClassId,CourseId,StartDate,EndDate,InstructorName,Location,SCSID")] ScheduledClass scheduledClass)
        {
            if (ModelState.IsValid)
            {
                db.ScheduledClasses.Add(scheduledClass);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", scheduledClass.CourseId);
            ViewBag.SCSID = new SelectList(db.ScheduledClassStatuses, "SCSID", "SCSName", scheduledClass.SCSID);
            return View(scheduledClass);
        }

        // GET: ScheduledClasses/Edit/5
        [Authorize(Roles = "Admin,Scheduler")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduledClass scheduledClass = db.ScheduledClasses.Find(id);
            if (scheduledClass == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", scheduledClass.CourseId);
            ViewBag.SCSID = new SelectList(db.ScheduledClassStatuses, "SCSID", "SCSName", scheduledClass.SCSID);
            return View(scheduledClass);
        }

        // POST: ScheduledClasses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,Scheduler")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ScheduledClassId,CourseId,StartDate,EndDate,InstructorName,Location,SCSID")] ScheduledClass scheduledClass)
        {
            if (ModelState.IsValid)
            {
                db.Entry(scheduledClass).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", scheduledClass.CourseId);
            ViewBag.SCSID = new SelectList(db.ScheduledClassStatuses, "SCSID", "SCSName", scheduledClass.SCSID);
            return View(scheduledClass);
        }

        // GET: ScheduledClasses/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id, int status)
        {
            Session["classStatus"] = db.ScheduledClassStatuses.Find(status).SCSName.ToUpper();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduledClass scheduledClass = db.ScheduledClasses.Find(id);
            if (scheduledClass == null)
            {
                return HttpNotFound();
            }
            return View(scheduledClass);
        }

        // POST: ScheduledClasses/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int status)
        {
            ScheduledClass scheduledClass = db.ScheduledClasses.Find(id);
            //db.ScheduledClasses.Remove(scheduledClass);
            scheduledClass.SCSID = status;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAT.UI.MVC/Views/ScheduledClasses/Create.cshtml
@model SAT.DATA.EF.ScheduledClass

@{
    ViewBag.Title = "Create a New Scheduled Class";
}


<div class="card card-body max1000 drop">
    <h2 class="text-center pb-4">@ViewBag.Title</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-6 inFix">
                    <div class="form-group">
                        @Html.LabelFor(model => model.CourseId, "Course Name", htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.SCSID, "Class Status", htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownList("SCSID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SCSID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6 inFix">
                    <div class="form-group">
                        @Html.LabelFor(model => model.InstructorName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.InstructorName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.InstructorName, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12 text-right">
                    <input type="submit" value="Save" class="btn btn-primary btn80" />
                    @*@Html.ActionLink("Cancel", "Index", "ScheduledClasses", new { @class = "btn btn-primary btn80 mr-0" })*@
                    <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-primary btn80 mr-0">Cancel</a>
                </div>
            </div>
        </div>
    }
</div>

SAT.UI.MVC/Views/ScheduledClasses/Delete.cshtml
@model SAT.DATA.EF.ScheduledClass

@{
    ViewBag.Title = "Delete: " + @Model.ScheduledClassDesc;
}

<div class="card card-body max800 drop">
    <h2 class="text-center pb-2">@ViewBag.Title</h2>
         <div class="pt-5 pb-5 divCenter">
            <dl class="dl-horizontal">
                <dd>
                    <span class="font-weight-bold pr-2">Course Name:</span>@Html.DisplayFor(model => model.Course.CourseName)
                </dd>
                <dd>
                    <span class="font-weight-bold pr-2">Scheduled:</span> @Html.DisplayFor(model => model.StartDate) to @Html.DisplayFor(model => model.EndDate)
                </dd>
                <dd>
                    <span class="font-weight-bold pr-2">Instructor Name:</span>@Html.DisplayFor(model => model.InstructorName)
                </dd>
                <dd>
                    <span class="font-weight-bold pr-2">Location:</span>  @Html.DisplayFor(model => model.Location)
                </dd>
                <dd>
                    <span class="font-weight-bold pr-2">Status:</span>  @Html.DisplayFor(model => model.ScheduledClassStatus.SCSName)
                </dd>
            </dl>
        </div>
        <h3 class="text-center text-danger pb-4">Change class status to @Session["classStatus"]?</h3>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-actions no-color text-center">
            <input type="submit" value="Yes" class="btn btn-primary btn80" />
            @*@Html.ActionLink("No", "Index", "Courses", new { @class = "btn btn-primary btn80" })*@
            <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-primary btn80">No</a>
        </div>
        }
</div>

SAT.UI.MVC/Views/ScheduledClasses/Details.cshtml
@model SAT.DATA.EF.ScheduledClass

@{
    ViewBag.Title = "Class Details: " + @Model.ScheduledClassDesc;
}

<div class="card card-body max800 drop">
    <h2 class="text-center pb-2">@ViewBag.Title</h2>
    <div class="pt-5 pb-5 divCenter">
        <dl class="dl-horizontal">
            <dd>
                <span class="font-weight-bold pr-2">Course Name:</span>@Html.DisplayFor(model => model.Course.CourseName)
            </dd>
            <dd>
                <span class="font-weight-bold pr-2">Start Date:</span> @Html.DisplayFor(model => model.StartDate)
            </dd>
            <dd>
                <span class="font-weight-bold pr-2">End Date:</span>@Html.DisplayFor(model => model.EndDate)
            </dd>
            <dd>
                <span class="font-weight-bold pr-2">Instructor Name:</span>@Html.DisplayFor(model => model.InstructorName)
            </dd>
            <dd>
                <span class="font-weight-bold pr-2">Location:</span>  @Html.DisplayFor(model => model.Location)
            </dd>
            <dd>
                <span class="font-weight-bold pr-2">Status:</span>  @Html.DisplayFor(model => model.ScheduledClassStatus.SCSName)
            </dd>
        </dl>
    </div>
    <div class="col-md-12 text-center">
        @Html.ActionLink("Edit", "Edit", new { id = Model.CourseId }, new { @class = "btn btn-primary btn80" })
        @*@Html.ActionLink("Return", "Index", "Courses", new { @class = "btn btn-primary btn80" })*@
        <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-primary btn80 mr-0">Return</a>
    </div>
</div>

SAT.UI.MVC/Views/ScheduledClasses/Edit.cshtml
@model SAT.DATA.EF.ScheduledClass

@{
    ViewBag.Title = "Edit Class: " + @Model.ScheduledClassDesc;
}


<div class="card card-body max1000 drop">
    <h2 class="text-center pb-4">@ViewBag.Title</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ScheduledClassId)

            <div class="row">
                <div class="col-md-6 inFix">
                    <div class="form-group">
                        @Html.LabelFor(model => model.CourseId, "Course Name", htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.SCSID, "Class Status", htmlAttributes: new { @class = "control-label" })
                        @if (User.IsInRole("Admin"))
                        {

                            @Html.DropDownList("SCSID", null, htmlAttributes: new { @class = "form-control" })
                        }
                        else
                        {
                            @Html.DropDownList("SCSID", null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
                            @Html.HiddenFor(model => model.SCSID)
                        }
                        @Html.ValidationMessageFor(model => model.SCSID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6 inFix">
                    <div class="form-group">
                        @Html.LabelFor(model => model.InstructorName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.InstructorName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.InstructorName, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12 text-right">
                    <input type="submit" value="Save" class="btn btn-primary btn80" />
                    
                    @*@Html.ActionLink("Cancel", "Index", "ScheduledClasses", new { @class = "btn btn-primary btn80 mr-0" })*@
                    <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-primary btn80 mr-0">Cancel</a>
                </div>
            </div>
        </div>
    }
</div>

SAT.UI.MVC/Views/ScheduledClasses/Index.cshtml
@model IEnumerable<SAT.DATA.EF.ScheduledClass>

@{
    ViewBag.Title = "Scheduled Classes";
}


<div class="card card-body max1000 drop">
    <h2 class="text-center pb-4">@ViewBag.Title</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.StartDate)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Location)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Course.CourseName)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.ScheduledClassStatus.SCSName)
                </th>

                <th class="text-right">
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("Create New Class", "Create")
                    }
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Location)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course.CourseName)
                    </td>

                    <td class="text-center">
                        @if (User.IsInRole("Admin"))
                        {
                            <div class="dropdown d-inline">
                                <div href="#" class="btn btn-outline-primary btn-fw dropdown-toggle" data-toggle="dropdown">
                                    @* dropdown-toggle adds the down arrow *@
                                    @Html.DisplayFor(modelItem => item.ScheduledClassStatus.SCSName)
                                </div>

                                <div class="dropdown-menu" aria-haspopup="true" aria-expanded="false">
                                    @Html.ActionLink("Active", "Delete", new { id = item.ScheduledClassId, @status = 1 }, new { @class = "dropdown-item text-white" })
                                    @Html.ActionLink("Pending", "Delete", new { id = item.ScheduledClassId, @status = 2 }, new { @class = "dropdown-item text-white" })
                                    @Html.ActionLink("Completed", "Delete", new { id = item.ScheduledClassId, @status = 3 }, new { @class = "dropdown-item text-white" })
                                    @Html.ActionLink("Cancelled", "Delete", new { id = item.ScheduledClassId, @status = 4 }, new { @class = "dropdown-item text-white" })
                                </div>
                            </div>
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.ScheduledClassStatus.SCSName)
                        }
                    </td>

                    <td class="text-right">

                        @Html.ActionLink("Edit", "Edit", new { id = item.ScheduledClassId }) <span>|</span>
                        @Html.ActionLink("Details", "Details", new { id = item.ScheduledClassId })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>